### ISSUE TITLE
Regex mailbox names / parse subfolders

### ISSUE THREAD

**Issue by simon-bre** [axllent/imap-scrub#9]
Hi, great tool you made here! Just a little suggestion:

When a mailbox has subfolders, they are listed as separate mailboxes, e.g.:
INBOX.abc
INBOX.xyz
...
When people like to create sophisticated directory trees for their mails with hundreds of folders, it seems kind of tedious to clean their mailboxes with this tool... so I think either support for parsing all subfolders or parsing e.g. all folders that match a regex such as INBOX.* would be awesome.

Cheers

**Comment by nanawel** [comment]
For what it's worth, I'm sharing the recipe I needed to clean up my mailbox, where I have a _lot_ of folders.

First get the list of the folders (mailboxes):

```shell
./imap-scrub -m config.yml
- folder 1
- folder Z
- INBOX.somename
```

The output format is valid YAML, which is very handy (it's just a list actually).

Then use [Cyberchef+jq](https://www.cyberchef.dev/cyberchef) to generate your rules. For me it was `if > 720 days then remove_attachements`:

```
YAML_to_JSON()
Jq('.[] | {mailbox: ., older_than: 720, actions: "remove_attachments"}')
JSON_to_YAML()
```

Use "Load recipe" and paste the code above, then paste your own list of mailboxes in the "Input" panel.
You should get the following output with my example, but you can easily tune it if needed:

```yaml
- mailbox: folder 1
  older_than: 720
  actions: remove_attachments
- mailbox: folder Z
  older_than: 720
  actions: remove_attachments
- mailbox: INBOX.somename
  older_than: 720
  actions: remove_attachments
```
